name: PR build

on:
  workflow_dispatch:
  pull_request:
    branches: [main, release/0.2.x]
  push:
    branches:
      - release/0.2.x

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Read Maven version
        id: maven-version
        run: echo "version=$(cat .github/vars/maven-version.txt)" >> $GITHUB_OUTPUT

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.13'

      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1

  maven-build:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        java: [17, 21, 25]
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Install docker-credential-fake
        run: |
          sudo cp docker-credential-fake /usr/bin/docker-credential-fake

      - name: Read Maven version
        id: maven-version
        run: echo "version=$(cat .github/vars/maven-version.txt)" >> $GITHUB_OUTPUT

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@6c4e9964d4ecb8f1026310cd8618791fd51a8016 # v1.19.0
        with:
          checkout-enabled: false
          java-distribution: 'temurin'
          java-version: ${{ matrix.java }}
          maven-version: ${{ steps.maven-version.outputs.version }}
          cache-enabled: true

      - name: Maven build
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload coverage reports to Codecov
        if: matrix.java == '17'
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
